#!/bin/bash

mkdir src
cd src

git clone https://github.com/mosdef-hub/mbuild.git
cd mbuild
pip install .
cd ..

git clone https://github.com/mosdef-hub/nanoparticle_optimization.git
cd nanoparticle_optimization
pip install .
cd ..
